import { create } from "zustand";

const translations = {
  es: {
    nav: {
      home: "Inicio",
      blog: "Blog",
      reel: "Reel",
      installer: "Instalador",
      platform: "Plataforma",
    },
    hero: {
      title: "Espacios físicos",
      subtitle: "medibles, vivos y accionables",
      desc: "Aitanna.ai es una plataforma de analítica avanzada y gestión de datos en tiempo real diseñada para entender cómo se mueven las personas en espacios físicos complejos.",
    },
    what: {
      title: "¿Qué hace Aitanna?",
      desc: "Es el punto central donde convergen todos los datos recogidos por los nodos instalados en un espacio: los procesa, los estructura y los transforma en gráficos, estadísticas y métricas claras.",
      card1_title: "Centralización",
      card1_desc:
        "Aitanna.ai es la plataforma donde se centralizan todos los datos generados por los nodos instalados en un espacio físico.",
      card2_title: "Procesamiento",
      card2_desc:
        "La plataforma recibe esta información, la procesa y la organiza para ofrecer una visión clara y estructurada del comportamiento de las personas.",
      card3_title: "Visualización",
      card3_desc:
        "A través de dashboards visuales, analiza el tráfico por zonas, detecta patrones y toma decisiones basadas en datos reales.",
    },
    summary: {
      title: "En resumen",
      step1: "Cuánta gente hay",
      label1: "Volumen",
      step2: "Dónde está",
      label2: "Ubicación",
      step3: "A qué hora",
      label3: "Tiempo",
      step4: "Cómo se mueve",
      label4: "Flujo",
      fits: "Aitanna.ai encaja.",
      fits_desc:
        "Y además, permite interactuar con los usuarios cuando están en la zona y el momento adecuados.",
    },
    sectors: {
      title: "Sectores Multizona",
      desc: "Aitanna.ai se adapta a cualquier espacio donde sea clave analizar el tráfico de personas. Gracias a su enfoque multizona, no hay límites.",
      hosp_title: "Hospitality & Turismo",
      hosp_desc: "Hoteles, resorts, beach clubs, campings.",
      hosp_items: [
        "Habitaciones y villas",
        "Restaurantes y bares",
        "Piscinas, spa y gimnasio",
        "Playa, zonas exteriores y accesos",
      ],
      retail_title: "Retail & Comercio",
      retail_desc: "Tiendas, flagship stores, grandes superficies.",
      retail_items: [
        "Exterior y zonas de atracción",
        "Entrada, pasillos y áreas de producto",
        "Probadores y cajas",
      ],
      fuel_title: "Estaciones de servicio",
      fuel_desc: "Gasolineras, áreas de descanso, hubs de transporte.",
      fuel_items: [
        "Surtidores y Tienda",
        "Cafetería y baños",
        "Accesos y exterior",
      ],
      malls_title: "Centros Comerciales",
      malls_desc: "Malls, outlets, complejos corporativos.",
      malls_items: [
        "Zonas, plantas y accesos",
        "Flujos entre áreas",
        "Puntos calientes y zonas infrautilizadas",
      ],
      events_title: "Eventos & Espacios",
      events_desc: "Ferias, congresos, estadios, parques temáticos.",
      events_items: [
        "Control de afluencia por zonas",
        "Picos de tráfico",
        "Recorridos y distribución",
      ],
    },
    clients: {
      title: "Empresas que confían en nosotros",
    },
    blog: {
      title: "Últimas Noticias",
      category: "Tecnología",
      read_more: "Leer más",
      desc_placeholder:
        "Un resumen breve sobre el contenido interesante que Aitanna tiene para ofrecer y cómo la analítica de datos transforma espacios.",
    },
    reel: {
      title: "Aitanna en Movimiento",
      subtitle: "Descubre nuestra visión a través de nuestros reels.",
      watch: "Ver Video",
    },
  },
  en: {
    nav: {
      home: "Home",
      blog: "Blog",
      reel: "Reel",
      installer: "Installer",
      platform: "Platform",
    },
    hero: {
      title: "Physical spaces",
      subtitle: "measurable, alive and actionable",
      desc: "Aitanna.ai is an advanced analytics and real-time data management platform designed to understand how people move in complex physical spaces.",
    },
    what: {
      title: "What does Aitanna do?",
      desc: "It is the central point where all data collected by nodes installed in a space converge: processing, structuring, and transforming them into clear charts, statistics, and metrics.",
      card1_title: "Centralization",
      card1_desc:
        "Aitanna.ai is the platform where all data generated by nodes installed in a physical space are centralized.",
      card2_title: "Processing",
      card2_desc:
        "The platform receives this information, processes it, and organizes it to offer a clear and structured view of people's behavior.",
      card3_title: "Visualization",
      card3_desc:
        "Through visual dashboards, it analyzes traffic by zones, detects patterns, and makes decisions based on real data.",
    },
    summary: {
      title: "In summary",
      step1: "How many people",
      label1: "Volume",
      step2: "Where are they",
      label2: "Location",
      step3: "At what time",
      label3: "Time",
      step4: "How they move",
      label4: "Flow",
      fits: "Aitanna.ai fits.",
      fits_desc:
        "Furthermore, it allows interacting with users when they are in the right zone at the right time.",
    },
    sectors: {
      title: "Multizone Sectors",
      desc: "Aitanna.ai adapts to any space where analyzing people traffic is key. Thanks to its multizone approach, there are no limits.",
      hosp_title: "Hospitality & Tourism",
      hosp_desc: "Hotels, resorts, beach clubs, campsites.",
      hosp_items: [
        "Rooms and villas",
        "Restaurants and bars",
        "Pools, spa and gym",
        "Beach, outdoor areas and access",
      ],
      retail_title: "Retail & Commerce",
      retail_desc: "Stores, flagship stores, large surfaces.",
      retail_items: [
        "Exterior and attraction zones",
        "Entrance, aisles and product areas",
        "Fitting rooms and checkout",
      ],
      fuel_title: "Service Stations",
      fuel_desc: "Gas stations, rest areas, transport hubs.",
      fuel_items: [
        "Pumps and Shop",
        "Cafeteria and restrooms",
        "Access and exterior",
      ],
      malls_title: "Shopping Malls",
      malls_desc: "Malls, outlets, corporate complexes.",
      malls_items: [
        "Zones, floors and access",
        "Flows between areas",
        "Hotspots and underused zones",
      ],
      events_title: "Events & Spaces",
      events_desc: "Fairs, congresses, stadiums, theme parks.",
      events_items: [
        "Crowd control by zones",
        "Traffic peaks",
        "Routes and distribution",
      ],
    },
    clients: {
      title: "Companies that trust us",
    },
    blog: {
      title: "Latest News",
      category: "Technology",
      read_more: "Read more",
      desc_placeholder:
        "A brief summary of the interesting content Aitanna has to offer and how data analytics transforms spaces.",
    },
    reel: {
      title: "Aitanna in Motion",
      subtitle: "Discover our vision through our reels.",
      watch: "Watch Video",
    },
  },
};

export const useLanguageStore = create((set, get) => ({
  language: "es",

  toggleLanguage: () =>
    set((state) => ({
      language: state.language === "es" ? "en" : "es",
    })),

  t: (path) => {
    const lang = get().language;
    const keys = path.split(".");
    let text = translations[lang];

    for (let key of keys) {
      if (text[key] === undefined) return path;
      text = text[key];
    }
    return text;
  },
}));
